# Generated by Django 4.2.2 on 2023-06-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='is_watched',
            field=models.BooleanField(default=False),
        ),
    ]
