# Generated by Django 4.2.2 on 2023-06-11 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_topics_is_watched'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topics',
            options={'ordering': ['author', 'date_created'], 'verbose_name': 'topic', 'verbose_name_plural': 'topics'},
        ),
    ]
