# Generated by Django 4.2.2 on 2023-06-25 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_alter_topics_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topics',
            options={'ordering': ['date_created'], 'verbose_name': 'topic', 'verbose_name_plural': 'topics'},
        ),
        migrations.AlterField(
            model_name='topics',
            name='author',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topics',
            name='is_watched',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
